/// Supabase Feedback Service
/// Persists feedback, bug reports, and feature requests to Supabase
library;

import 'package:flutter/foundation.dart';
import '../core/utils/logger.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

/// Feedback types
enum FeedbackType {
  bug,
  feature,
  general;

  String get displayName => switch (this) {
        FeedbackType.bug => 'Bug Report',
        FeedbackType.feature => 'Feature Request',
        FeedbackType.general => 'General Feedback',
      };
}

/// Feedback status
enum FeedbackStatus {
  open,
  inProgress,
  resolved,
  closed;

  String get displayName => switch (this) {
        FeedbackStatus.open => 'Open',
        FeedbackStatus.inProgress => 'In Progress',
        FeedbackStatus.resolved => 'Resolved',
        FeedbackStatus.closed => 'Closed',
      };
}

/// Feedback submission model
class FeedbackSubmission {
  final String id;
  final String userId;
  final FeedbackType type;
  final String title;
  final String description;
  final String? screenName;
  final int? rating;
  final FeedbackStatus status;
  final DateTime createdAt;
  final DateTime? resolvedAt;
  final String? adminNotes;

  const FeedbackSubmission({
    required this.id,
    required this.userId,
    required this.type,
    required this.title,
    required this.description,
    this.screenName,
    this.rating,
    this.status = FeedbackStatus.open,
    required this.createdAt,
    this.resolvedAt,
    this.adminNotes,
  });

  factory FeedbackSubmission.fromJson(Map<String, dynamic> json) {
    return FeedbackSubmission(
      id: json['id'].toString(),
      userId: json['user_id']?.toString() ?? '',
      type: _parseType(json['type']?.toString() ?? 'general'),
      title: json['title']?.toString() ?? '',
      description: json['description']?.toString() ?? '',
      screenName: json['screen_name']?.toString(),
      rating: json['rating'] is int ? json['rating'] : null,
      status: _parseStatus(json['status']?.toString() ?? 'open'),
      createdAt: DateTime.tryParse(json['created_at']?.toString() ?? '') ?? DateTime.now(),
      resolvedAt: json['resolved_at'] != null
          ? DateTime.tryParse(json['resolved_at'].toString())
          : null,
      adminNotes: json['admin_notes']?.toString(),
    );
  }

  Map<String, dynamic> toJson() => {
        'user_id': userId,
        'type': type.name,
        'title': title,
        'description': description,
        'screen_name': screenName,
        'rating': rating,
        'status': status.name,
        'created_at': createdAt.toIso8601String(),
        'resolved_at': resolvedAt?.toIso8601String(),
        'admin_notes': adminNotes,
      };

  static FeedbackType _parseType(String type) {
    return FeedbackType.values.firstWhere(
      (t) => t.name == type.toLowerCase(),
      orElse: () => FeedbackType.general,
    );
  }

  static FeedbackStatus _parseStatus(String status) {
    return FeedbackStatus.values.firstWhere(
      (s) => s.name == status.toLowerCase(),
      orElse: () => FeedbackStatus.open,
    );
  }
}

/// Supabase Feedback Service - Persists to database
class SupabaseFeedbackService extends ChangeNotifier {
  static final SupabaseFeedbackService _instance = SupabaseFeedbackService._internal();
  static SupabaseFeedbackService get instance => _instance;

  SupabaseFeedbackService._internal();

  final _client = Supabase.instance.client;
  static const _table = 'feedback_submissions';

  List<FeedbackSubmission> _submissions = [];
  bool _isLoading = false;
  String? _error;

  List<FeedbackSubmission> get submissions => List.unmodifiable(_submissions);
  bool get isLoading => _isLoading;
  String? get error => _error;

  /// Submit a bug report
  Future<bool> submitBugReport({
    required String userId,
    required String title,
    required String description,
    String? screenName,
  }) async {
    return _submit(FeedbackSubmission(
      id: '', // Generated by Supabase
      userId: userId,
      type: FeedbackType.bug,
      title: title,
      description: description,
      screenName: screenName,
      createdAt: DateTime.now(),
    ));
  }

  /// Submit a feature request
  Future<bool> submitFeatureRequest({
    required String userId,
    required String title,
    required String description,
  }) async {
    return _submit(FeedbackSubmission(
      id: '',
      userId: userId,
      type: FeedbackType.feature,
      title: title,
      description: description,
      createdAt: DateTime.now(),
    ));
  }

  /// Submit general feedback
  Future<bool> submitGeneralFeedback({
    required String userId,
    required String description,
    int? rating,
  }) async {
    return _submit(FeedbackSubmission(
      id: '',
      userId: userId,
      type: FeedbackType.general,
      title: 'General Feedback',
      description: description,
      rating: rating,
      createdAt: DateTime.now(),
    ));
  }

  /// Submit a content report (forum post, club, etc.)
  Future<bool> submitReport({
    required String userId,
    required String contentType,
    required String contentId,
    required String reason,
    String? additionalDetails,
  }) async {
    final title = 'Report: $contentType';
    final description = '''
Reported Content:
- Type: $contentType
- ID: $contentId
- Reason: $reason
${additionalDetails != null ? '\nAdditional Details:\n$additionalDetails' : ''}
''';

    return _submit(FeedbackSubmission(
      id: '',
      userId: userId,
      type: FeedbackType.general,
      title: title,
      description: description,
      createdAt: DateTime.now(),
    ));
  }

  /// Internal submit method
  Future<bool> _submit(FeedbackSubmission submission) async {
    _isLoading = true;
    _error = null;
    notifyListeners();

    try {
      final response = await _client
          .from(_table)
          .insert(submission.toJson())
          .select()
          .single();

      final newSubmission = FeedbackSubmission.fromJson(response);
      _submissions.insert(0, newSubmission);
      
      _isLoading = false;
      notifyListeners();
      return true;
    } catch (e) {
      AppLogger.error(' Error submitting feedback: $e');
      _error = 'Failed to submit. Please try again.';
      _isLoading = false;
      notifyListeners();
      return false;
    }
  }

  /// Fetch user's submissions
  Future<void> fetchUserSubmissions(String userId) async {
    _isLoading = true;
    _error = null;
    notifyListeners();

    try {
      final response = await _client
          .from(_table)
          .select()
          .eq('user_id', userId)
          .order('created_at', ascending: false);

      _submissions = (response as List)
          .map((json) => FeedbackSubmission.fromJson(json))
          .toList();
      
      _isLoading = false;
      notifyListeners();
    } catch (e) {
      AppLogger.error(' Error fetching feedback: $e');
      _error = 'Failed to load submissions.';
      _isLoading = false;
      notifyListeners();
    }
  }

  /// Fetch all submissions (admin only)
  Future<void> fetchAllSubmissions() async {
    _isLoading = true;
    _error = null;
    notifyListeners();

    try {
      final response = await _client
          .from(_table)
          .select()
          .order('created_at', ascending: false);

      _submissions = (response as List)
          .map((json) => FeedbackSubmission.fromJson(json))
          .toList();
      
      _isLoading = false;
      notifyListeners();
    } catch (e) {
      AppLogger.error(' Error fetching all feedback: $e');
      _error = 'Failed to load submissions.';
      _isLoading = false;
      notifyListeners();
    }
  }

  /// Get submissions by status
  List<FeedbackSubmission> getByStatus(FeedbackStatus status) {
    return _submissions.where((s) => s.status == status).toList();
  }

  /// Get submissions by type
  List<FeedbackSubmission> getByType(FeedbackType type) {
    return _submissions.where((s) => s.type == type).toList();
  }
}
